In [3]:
import pandas as pd
print(pd.__version__)

3.0.3

In [5]:
df = pd.read_csv("../data/sales_raw_dirty.csv")
duplicate_count = df.duplicated().sum()
print(duplicate_count)

30

In [6]:
print("Shape before cleaning")
print(df.shape)

Shape before cleaning
(1030, 13)

In [8]:
df=df.drop_duplicates()
print("After drop duplicates")
print(df.shape)
print(df.duplicated().sum())

After drop duplicates
(1000, 13)
0

In [9]:
df["Customer_Name"]=df["Customer_Name"].fillna("Unknown")
df["Customer_Name"].isnull().sum()

np.int64(0)

In [10]:
price_lookup = {
    "Laptop": 55000,
    "Smartphone": 30000,
    "Headphones": 2500,
    "Keyboard": 1500,
    "Monitor": 12000,
    "Printer": 8000,
    "Mouse": 700,
    "Smartwatch": 5000
}

df["Unit_Price"]=df["Unit_Price"].fillna(df["Product"].map(price_lookup))
df["Unit_Price"].isnull().sum()

np.int64(0)

In [11]:
df["Customer_Name"].head(10)

0        Amit Kumar
1      Anjali Menon
2      Anjali Menon
3       Neha Kapoor
4      Vikram Singh
5     Anjali Menon
6      Vikram Singh
7        Priya Nair
8      Rahul Sharma
9        Amit Kumar
Name: Customer_Name, dtype: str

In [14]:
df["Customer_Name"]=df["Customer_Name"].str.strip()

In [15]:
df["Payment_Method"].unique()

<StringArray>
[        'UPI',  'Debit Card',        'Cash', 'Net Banking', 'Credit Card',
         'Upi',        'CASH', 'net banking',  'DEBIT CARD', 'NET BANKING',
        'cash',         'upi', 'CREDIT CARD',  'debit card', 'credit card']
Length: 15, dtype: str

In [18]:
df["Payment_Method"].str.strip().str.title()
df["Payment_Method"]=df["Payment_Method"].replace({"Upi":"UPI"})
df["Payment_Method"].head(10)

0            UPI
1     Debit Card
2           Cash
3     Debit Card
4     Debit Card
5            UPI
6     Debit Card
7    Net Banking
8    Credit Card
9    Credit Card
Name: Payment_Method, dtype: str

In [23]:
df["Quantity"].describe()
df[df["Quantity"]<0]

,Order_ID,Order_Date,Customer_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Payment_Method,Order_Status,Sales
2,ORD000501,2025-04-07,CUST000501,Anjali Menon,Delhi,Smartphone,Electronics,-4,30000.0,15,Cash,Cancelled,25500.0
15,ORD000012,2025-01-22,CUST000012,Arjun Menon,Bengaluru,Laptop,Electronics,-3,55000.0,15,Net Banking,Returned,93500.0
31,ORD000568,2025-02-27,CUST000568,Meera Iyer,Kochi,Mouse,Accessories,-3,700.0,15,Net Banking,Delivered,2380.0
87,ORD000722,2025-12-04,CUST000722,Arjun Menon,Kochi,Mouse,Accessories,-2,700.0,5,UPI,Returned,2660.0
115,ORD000354,2025-09-03,CUST000354,Anjali Menon,Kochi,Laptop,Electronics,-3,55000.0,10,Net Banking,Returned,198000.0
166,ORD000545,2025-12-30,CUST000545,Sneha Reddy,Pune,Laptop,Electronics,-5,55000.0,15,Credit Card,Returned,187000.0
197,ORD000930,2025-06-24,CUST000930,Neha Kapoor,Pune,Smartphone,Electronics,-3,30000.0,30,Net Banking,Cancelled,42000.0
222,ORD000194,2025-12-09,CUST000194,Priya Nair,Hyderabad,Headphones,Accessories,-2,2500.0,20,Credit Card,Delivered,4000.0
231,ORD000644,2025-07-31,CUST000644,Priya Nair,Kochi,Monitor,Electronics,-2,12000.0,10,UPI,Cancelled,43200.0
315,ORD000980,2025-02-18,CUST000980,Rahul Sharma,Hyderabad,Keyboard,Accessories,-3,1500.0,20,UPI,Cancelled,1200.0
374,ORD000061,2025-07-14,CUST000061,Amit Kumar,Delhi,Laptop,Electronics,-3,55000.0,5,Net Banking,Returned,52250.0
487,ORD000907,2025-01-21,CUST000907,Sanjay Das,Delhi,Smartwatch,Wearables,-4,5000.0,20,Net Banking,Cancelled,4000.0
513,ORD000237,2025-12-22,CUST000237,Priya Nair,Bengaluru,Monitor,Electronics,-1,12000.0,5,Debit Card,Cancelled,11400.0
549,ORD000337,2025-03-11,CUST000337,Sneha Reddy,Delhi,Keyboard,Accessories,-1,1500.0,10,Net Banking,Returned,4050.0
587,ORD000280,2025-03-30,CUST000280,Sanjay Das,Pune,Headphones,Accessories,-1,2500.0,20,Debit Card,Cancelled,2000.0
693,ORD000199,2025-07-20,CUST000199,Neha Kapoor,Delhi,Monitor,Electronics,-5,12000.0,15,Debit Card,Returned,10200.0
755,ORD000970,2025-11-01,CUST000970,Sneha Reddy,Hyderabad,Monitor,Electronics,-1,12000.0,15,Debit Card,Cancelled,40800.0
767,ORD000764,2025-04-04,CUST000764,Unknown,Coimbatore,Mouse,Accessories,-3,700.0,5,Net Banking,Delivered,2660.0
915,ORD000516,2025-09-14,CUST000516,Vikram Singh,Chennai,Smartphone,Electronics,-5,30000.0,20,DEBIT CARD,Cancelled,48000.0
999,ORD000654,2025-04-05,CUST000654,Arjun Menon,Bengaluru,Keyboard,Accessories,-2,1500.0,20,UPI,Returned,1200.0

In [24]:
df["Discount"].describe()
df[df["Discount"]>100]

,Order_ID,Order_Date,Customer_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Payment_Method,Order_Status,Sales
42,ORD000979,2025-08-16,CUST000979,Sneha Reddy,Delhi,Printer,Electronics,5,8000.0,131,UPI,Delivered,32000.0
45,ORD000439,2025-06-17,CUST000439,Sanjay Das,Delhi,Mouse,Accessories,1,700.0,149,UPI,Cancelled,595.0
57,ORD000044,2025-12-06,CUST000044,Neha Kapoor,Kochi,Keyboard,Accessories,2,1500.0,115,UPI,Returned,2550.0
74,ORD000900,2025-04-02,CUST000900,Priya Nair,Hyderabad,Mouse,Accessories,2,700.0,135,UPI,Delivered,1120.0
77,ORD000023,2025-10-20,CUST000023,Sneha Reddy,Bengaluru,Keyboard,Accessories,1,1500.0,129,Cash,Returned,1275.0
93,ORD000991,2025-02-06,CUST000991,Priya Nair,Mumbai,Headphones,Accessories,5,2500.0,129,Cash,Returned,11250.0
173,ORD000204,2025-07-14,CUST000204,Sneha Reddy,Coimbatore,Printer,Electronics,5,8000.0,115,UPI,Cancelled,36000.0
327,ORD000261,2025-12-09,CUST000261,Rahul Sharma,Delhi,Smartwatch,Wearables,3,5000.0,133,UPI,Returned,13500.0
336,ORD000293,2025-01-29,CUST000293,Neha Kapoor,Bengaluru,Keyboard,Accessories,4,1500.0,132,Net Banking,Returned,5400.0
354,ORD000400,2025-07-20,CUST000400,Sneha Reddy,Coimbatore,Printer,Electronics,2,8000.0,146,Debit Card,Returned,12800.0
489,ORD000540,2025-03-28,CUST000540,Anjali Menon,Delhi,Smartphone,Electronics,2,30000.0,110,UPI,Delivered,54000.0
508,ORD000258,2025-10-28,CUST000258,Amit Kumar,Pune,Monitor,Electronics,3,12000.0,129,Net Banking,Delivered,25200.0
576,ORD000817,2025-03-25,CUST000817,Priya Nair,Coimbatore,Monitor,Electronics,4,12000.0,148,Debit Card,Cancelled,45600.0
595,ORD000910,2025-03-19,CUST000910,Unknown,Pune,Monitor,Electronics,4,12000.0,131,UPI,Returned,38400.0
706,ORD000208,2025-02-02,CUST000208,Rahul Sharma,Kochi,Laptop,Electronics,2,55000.0,112,UPI,Cancelled,88000.0
780,ORD000056,2025-10-26,CUST000056,Anjali Menon,Mumbai,Mouse,Accessories,5,700.0,148,Cash,Returned,2975.0
826,ORD000264,2025-07-10,CUST000264,Rahul Sharma,Mumbai,Smartwatch,Wearables,3,5000.0,142,Credit Card,Returned,10500.0
856,ORD000737,2025-08-11,CUST000737,Meera Iyer,Coimbatore,Keyboard,Accessories,5,1500.0,135,Cash,Cancelled,7125.0
902,ORD000367,2025-03-11,CUST000367,Priya Nair,Delhi,Headphones,Accessories,3,2500.0,139,Cash,Returned,6375.0
1007,ORD000692,2025-02-27,CUST000692,Rahul Sharma,Pune,Smartwatch,Wearables,3,5000.0,136,Debit Card,Delivered,14250.0

In [ ]:
print("Before cleaning",df.shape)
df=df[df["Quantity"]>0]
df=df[df["Discount"]<=100]
print("After cleaning",df.shape)
print("\nMinimum Quantity")
print(df["Quantity"].min())
print("Maximum discount")
print(df["Discount"].max())

Before cleaning (1000, 13)
After cleaning (960, 13)

Minimum Quantity
1
Maximum discount
30

In [26]:
print(df.isnull().sum())
print(df.duplicated().sum())
print(df.describe())

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
City              0
Product           0
Category          0
Quantity          0
Unit_Price        0
Discount          0
Payment_Method    0
Order_Status      0
Sales             0
dtype: int64
0
         Quantity    Unit_Price    Discount          Sales
count  960.000000    960.000000  960.000000     960.000000
mean     2.932292  14227.708333   16.130208   35124.593750
std      1.423986  17903.653717    8.007994   52980.998995
min      1.000000    700.000000    5.000000     490.000000
25%      2.000000   1500.000000   10.000000    4162.500000
50%      3.000000   5000.000000   15.000000   11200.000000
75%      4.000000  12000.000000   20.000000   38500.000000
max      5.000000  55000.000000   30.000000  261250.000000

In [28]:
df.to_csv("../data/cleaned/sales_clean.csv",index=False)
print("Cleaned Successfully")

Cleaned Successfully